dotfiles_oh_my_zsh_repo: https://github.com/ohmyzsh/ohmyzsh.git
dotfiles_oh_my_zsh_dir: "{{ dotfiles_home }}/.oh-my-zsh"
dotfiles_oh_my_zsh_custom: "{{ dotfiles_oh_my_zsh_dir }}/custom"
dotfiles_powerlevel10k_repo: https://github.com/romkatv/powerlevel10k.git
dotfiles_powerlevel10k_dir: "{{ dotfiles_oh_my_zsh_custom }}/themes/powerlevel10k"
