---
- name: Install desktop assets
  when:
    - ansible_system == "Linux"
    - dotfiles_enable_desktop_entries | bool
  block:
    - name: Import Guake preferences
      ansible.builtin.shell: "dconf load /apps/guake/ < {{ dotfiles_files_dir }}/guake/guake.dconf"
      args:
        executable: /bin/bash
      changed_when: false
      when:
        - dotfiles_enable_guake | bool
        - ansible_env.DISPLAY is defined
