dotfiles_base_packages_common:
  - git
  - curl
  - wget
  - zsh
  - vim
  - stow
  - just

dotfiles_base_packages_debian:
  - ca-certificates
  - dconf-cli
  - gnupg
  - python3-pip
  - guake

dotfiles_base_packages_arch:
  - base-devel
  - dconf
  - python-pip
  - guake

dotfiles_linuxbrew_prefix: /home/linuxbrew/.linuxbrew
dotfiles_linuxbrew_prereq_packages_debian:
  - build-essential
  - file
  - procps
dotfiles_linuxbrew_prereq_packages_arch:
  - file
  - procps-ng
dotfiles_linuxbrew_packages:
  - codex
  - difftastic
  - diff-so-fancy

dotfiles_enable_nerd_fonts: true
dotfiles_nerd_fonts_cache_dir: "{{ dotfiles_home }}/.local/state/dotfiles/nerd-fonts"
dotfiles_nerd_fonts_install_dir: "{{ dotfiles_home }}/.local/share/fonts"
dotfiles_nerd_fonts_version: 3.4.0
dotfiles_nerd_fonts:
  - name: Hack
    archive: Hack.zip
  - name: Meslo
    archive: Meslo.zip

dotfiles_base_packages_macos:
  - curl
  - difftastic
  - diff-so-fancy
  - direnv
  - gh
  - git
  - just
  - lsd
  - openjdk@17
  - pyenv
  - pyenv-virtualenv
  - rust
  - stow
  - tig
  - vim
  - wget
  - zsh

dotfiles_base_casks_macos:
  - font-hack-nerd-font
