dotfiles_base_packages_common:
  - git
  - curl
  - wget
  - zsh
  - vim
  - stow
  - just

dotfiles_base_packages_debian:
  - ca-certificates
  - dconf-cli
  - gnupg
  - python3-pip
  - guake

dotfiles_base_packages_arch:
  - base-devel
  - dconf
  - python-pip
  - guake

dotfiles_linuxbrew_prefix: /home/linuxbrew/.linuxbrew
dotfiles_linuxbrew_packages:
  - codex
  - difftastic

dotfiles_base_packages_macos:
  - curl
  - difftastic
  - diff-so-fancy
  - direnv
  - gh
  - git
  - just
  - lsd
  - openjdk@17
  - pyenv
  - pyenv-virtualenv
  - rust
  - stow
  - tig
  - vim
  - wget
  - zsh

dotfiles_base_casks_macos:
  - font-hack-nerd-font
