dotfiles_desktop_bin_dir: /usr/local/bin
dotfiles_desktop_applications_dir: /usr/local/share/applications
dotfiles_desktop_wrappers:
  - code
  - subl
dotfiles_static_desktop_entries:
  - code.desktop
  - python2.7.desktop
  - python3.6.desktop
  - sublime_text.desktop
dotfiles_removed_desktop_wrappers:
  - clion
  - intellij
  - pycharm
  - rider
  - webstorm
dotfiles_removed_desktop_entries:
  - clion.desktop
  - intellij.desktop
  - pycharm.desktop
  - rider.desktop
  - webstorm.desktop
